version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    container_name: healthcare_classification_app

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    container_name: mongo_db
